---
services:
  taifex-web:
    image: httpd:latest
    container_name: taifex-web-container
    ports:
      - "8080:80"  # Serve web files on http://host:8080
    volumes:
      - ../taifex_web:/usr/local/apache2/htdocs/

  taifex-selenium:
    build:
      context: .
      dockerfile: Dockerfile.seleniumbase
    image: taifex-selenium-app  # Custom image name if build via "Dockerfile"
    container_name: taifex-selenium-container
    volumes:
      - ../taifex_daily:/root/git/taifex_daily
      - ../taifex_web:/root/git/taifex_web
    working_dir: /root
    stdin_open: true
    tty: true

#  taifex-vnc:
#    # image: mrcolorrain/vnc-browser:debian
#    build:
#      context: .
#      dockerfile: Dockerfile.vnc  # point to Dockerfile
#    container_name: taifex-vnc
#    ports:
#      - "5900:5900"        # VNC Viewer
#      - "6080:6080"          # Web access: http://host:6080
#    volumes:
#      - ./taifex_daily:/git/taifex_daily
#    environment:
#      - VNC_PASSWORD=p@ssw0rd
#    #   - USER=zane
#    #   - HTTP_PASSWORD=p@ssw0rd
#    restart: unless-stopped
#    shm_size: 2g

